language: java
notifications:
  email: false
deploy:
  skip_cleanup: true
  provider: heroku
  app: spark-example-sheilaom
  api_key:
    secure: OoDhua1RP2e1+4SR2PXh5DhcfgKN1bHUCw/CZu7d43WOvBwnhxuegVQ/AbVHw88ym9ZNTcapy4ol52chaeUNMFoQiSFHzq+l4p+/G2I/2C5cSuzCvSNGC1PSNCCtaacXHdzvrh0bc8trjRyuvhNOQdj8bb2VnN2UDSjlnfHYD6fd9E7XSK/AUylOhT+7Vjybqij4tC+a31w/hzSD0G8GMsXVwHFUIrI+dx92r35xgLGHpQ7RhF/SwGdvQfGljAQz2u4of5+EFAT0hDXZU5I7o33gNk0myHqVn+aIBHj17v9QEfSG00dHJjZPe9DdI5uXkw5XXhCSc3NSYvKg3lOY6ymA/Wx9XzWBzR01Bj3r9qfOnAan3Z/jzq55dQEkozi2qBsPbR5wGarzPM7fMKmv143CZcfNSjSK2KOs/I3jb1dKx/RYxeR0bh/4twNbVWjkoaFlEYQd8upy1qmUKQyA4fo+V2uTVF7+2ZUd/c+IwmPUYcpGgBEw7uyKy0hRVir/nRs9x6x2AnWHpMUFiPPLV9Ux6aqt0s60Z8yUoxEHhGJZK6sv/dOx2IG+7nufQtGYRk2smYixWHMvFeXhHqkaJGiu+lCgNDo7OJtUQTBehWKDfWAfhmmUhJJsdP8yjXkvTssnZWzr82EISyPbV5E/Ykv8OxhqSViKPBlmYW6Lnu4=
